#!/usr/bin/env python3
"""Write refs.bib straight from the arXiv-verified metadata.

Author lists, titles and years are whatever arXiv returned, never retyped, so a
citation cannot drift from the paper it points at.
"""
import json, re, sys

v = json.load(open("/tmp/verified.json"))
KEYS = {}
def key(g):
    last = g["authors"][0].split()[-1]
    last = re.sub(r"[^A-Za-z]", "", last).lower()
    yr = g["published"][:4]
    word = next((w for w in re.findall(r"[A-Za-z]{4,}", g["title"])
                 if w.lower() not in {"with","from","that","this","using","towards","their"}), "x")
    k = f"{last}{yr}{word.lower()}"
    n = k
    i = 1
    while n in KEYS and KEYS[n] != g["id"]:
        i += 1; n = f"{k}{chr(96+i)}"
    KEYS[n] = g["id"]
    return n

def esc(s):
    return s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")

out, index = [], {}
for i, g in sorted(v.items(), key=lambda kv: kv[1]["published"]):
    k = key(g)
    index[k] = {"id": g["id"], "title": g["title"], "url": g["url"],
                "year": g["published"][:4], "first_author": g["authors"][0]}
    authors = " and ".join(g["authors"])
    out.append(
        f"@article{{{k},\n"
        f"  author  = {{{esc(authors)}}},\n"
        f"  title   = {{{esc(g['title'])}}},\n"
        f"  journal = {{arXiv:{g['id']}}},\n"
        f"  year    = {{{g['published'][:4]}}},\n"
        f"  url     = {{{g['url']}}}\n}}\n")

open("papers/refs.bib", "w").write(
    "% generated by scripts/make_bib.py from arXiv-verified metadata.\n"
    "% Every entry was confirmed against the arXiv API and its abs page opened.\n\n"
    + "\n".join(out))
json.dump(index, open("papers/refs_index.json", "w"), indent=1, ensure_ascii=False)
print(f"papers/refs.bib: {len(out)} entries")
for k, m in sorted(index.items(), key=lambda kv: kv[1]["year"]):
    print(f"  {k:<26} {m['year']}  {m['title'][:58]}")
