#!/usr/bin/env python3
"""Emit every number the paper cites as LaTeX macros, straight from results/.

Nothing in the paper is typed by hand: if a run did not happen, its macro is
absent and the build fails loudly rather than printing a stale or invented
value.
"""
import json, os, statistics as st, sys

R = "results"
def load(p):
    f = os.path.join(R, p, "results.json")
    return json.load(open(f)) if os.path.exists(f) else None

out = []
def mac(name, val, fmt="{:.4f}"):
    out.append(f"\\newcommand{{\\{name}}}{{{fmt.format(val) if isinstance(val,float) else val}}}")

main = load("E10b")
if main is None:
    sys.exit("results/E10b missing -- refusing to emit paper numbers")
pc = main["per_cutoff"]
CUTS = ["0.0","0.05","0.1","0.2","0.3","0.5","0.7","1.0"]
key = {"0.0":"Zero","0.05":"ZeroFive","0.1":"OneZero","0.2":"TwoZero",
       "0.3":"ThreeZero","0.5":"FiveZero","0.7":"SevenZero","1.0":"OneHundred"}

for c in CUTS:
    v = pc[c]
    mac(f"scMain{key[c]}", v["SC"]["mean"])
    mac(f"semMain{key[c]}", v["SC"]["sem"])
    mac(f"divMain{key[c]}", v["Diversity"]["mean"])
    mac(f"lpipsMain{key[c]}", v["LPIPS"]["mean"])
    mac(f"clipMain{key[c]}", v["CLIP"]["mean"], "{:.2f}")
    mac(f"edgeMain{key[c]}", v["EdgeF1"]["mean"])
    if v.get("FID") is not None:
        mac(f"fidMain{key[c]}", v["FID"], "{:.2f}")

# seeds
seeds = [("E10b",2026),("E13_seed2027",2027),("E13_seed2028",2028)]
for c in ["0.05","0.1","0.2","0.3","0.5","0.7"]:
    vals=[load(p)["per_cutoff"][c]["SC"]["mean"] for p,_ in seeds if load(p)]
    if len(vals)>1:
        mac(f"seedMean{key[c]}", st.mean(vals))
        mac(f"seedStd{key[c]}", st.stdev(vals))

# ablations at r=0.1 and r=0.3
for tag, path in [("Ea","E9a"),("Ecap","E10a"),("Ecapb","E10d"),("Ewin","E10c"),
                  ("Ebase","E1"),("Egate","E3h"),("Eres","E9b")]:
    d = load(path)
    if not d: continue
    for c in ["0.05","0.1","0.3"]:
        if c in d["per_cutoff"]:
            mac(f"sc{tag}{key[c]}", d["per_cutoff"][c]["SC"]["mean"])
    if "0.1" in d["per_cutoff"] and d["per_cutoff"]["0.1"].get("FID"):
        mac(f"fid{tag}", d["per_cutoff"]["0.1"]["FID"], "{:.2f}")

# injection-path decomposition
for tag, path in [("Both","E10b"),("SkipOnly","E10b_adapter_off"),
                  ("AttnOnly","E10b_skip_off"),("AllOff","E10b_all_off")]:
    d = load(path)
    if not d: continue
    for c in ["0.0","0.3"]:
        if c in d["per_cutoff"]:
            mac(f"path{tag}{key[c]}", d["per_cutoff"][c]["SC"]["mean"])
    if "0.0" in d["per_cutoff"] and d["per_cutoff"]["0.0"].get("FID"):
        mac(f"pathFid{tag}", d["per_cutoff"]["0.0"]["FID"], "{:.2f}")

# strength dial vs frequency dial
for s,nm in [("0.25","QuarterScale"),("0.5","HalfScale"),("0.75","ThreeQScale")]:
    d = load(f"E12_scale{s}")
    if not d: continue
    v = d["per_cutoff"]["0.1"]
    mac(f"sc{nm}", v["SC"]["mean"]); mac(f"div{nm}", v["Diversity"]["mean"])
    if v.get("FID"): mac(f"fid{nm}", v["FID"], "{:.2f}")

# specialists
for r in ["0.1","0.3","0.5","0.7"]:
    d = load(f"E2_r{r}")
    if not d: continue
    s = d["per_cutoff"][r]["SC"]; g = pc[r]["SC"]
    mac(f"spec{key[r]}", s["mean"])
    mac(f"specZ{key[r]}", (s["mean"]-g["mean"])/((s["sem"]**2+g["sem"]**2)**0.5), "{:+.1f}")

# baselines
for b in ["controlnet_canny","controlnet_hed"]:
    p = os.path.join(R, "baselines", f"{b}_native", "results.json")
    if not os.path.exists(p): continue
    d = json.load(open(p)); v = d["per_setting"]["native"]
    nm = "Canny" if "canny" in b else "Hed"
    mac(f"base{nm}Edge", v["EdgeF1"]["mean"]); mac(f"base{nm}Lpips", v["LPIPS"]["mean"])
    mac(f"base{nm}Clip", v["CLIP"]["mean"], "{:.2f}")
    if v.get("FID"): mac(f"base{nm}Fid", v["FID"], "{:.2f}")
    mac("baseParams", f"{d['provenance']['controlnet_params']:,}")

# VAE survival
for tag, f in [("Native","vae_survival_512.json"),("Up","vae_survival_256up.json")]:
    p = os.path.join(R, f)
    if not os.path.exists(p): continue
    k = json.load(open(p))["kept"]
    for c in ["0.1","0.3","0.7"]:
        if c in k: mac(f"vae{tag}{key[c]}", k[c]["mean"])

# sketch zero-shot
for tag, path in [("Face","E6_face"),("Scene","E6_scene")]:
    d = load(path)
    if not d: continue
    mac(f"sketch{tag}SC", d["SC_vs_input_sketch"]["mean"])
    mac(f"sketch{tag}Clip", d["CLIP"]["mean"], "{:.2f}")
    mac(f"sketch{tag}N", d["provenance"]["n_images"])
    if d.get("FID_vs_FFHQ") is not None:
        mac(f"sketch{tag}Fid", d["FID_vs_FFHQ"], "{:.2f}")

# model sizes
m = json.load(open("ckpt_dir/E10b_skip_inject/run_manifest.json"))
mac("ourParams", f"{m['trainable_params']:,}")
mac("ourParamsRatio", f"{361279120/m['trainable_params']:.0f}")
mac("nTrain", f"{m['n_train']:,}"); mac("nTest", f"{m['n_test']:,}")

os.makedirs("papers", exist_ok=True)
with open("papers/numbers.tex","w") as f:
    f.write("% generated by scripts/paper_numbers.py -- do not edit\n")
    f.write("\n".join(sorted(set(out))) + "\n")
print(f"papers/numbers.tex: {len(set(out))} macros from measured results")
